### ISSUE TITLE
"No such file" error when building the docs

### ISSUE THREAD

**Issue by gchaps** [elastic/docs#1379]
I'm getting an error when I build the docs.  I checked with another writer, and they are getting the error too. The error looks like this:

Traceback (most recent call last):
  File "./docs/build_docs", line 600, in <module>
    build_docker_image()
  File "./docs/build_docs", line 74, in build_docker_image
    build = common_popen(cmd, env={'DOCKER_BUILDKIT': '1'})
  File "./docs/build_docs", line 507, in common_popen
    env=env)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bmorelli25** [comment]
I'm able to reproduce this as well. @nik9000 I think this was introduced in 6c52c0e8067b12cf293ea253f1ee1f50457926f8. As a workaround I was able to check out c49b32ab0de2f3db43485112324c2804573b5e9c to get the doc build working again:
```
git checkout c49b32ab0de2f3db43485112324c2804573b5e9c
```

**Comment by nik9000** [comment]
I didn't have the error locally but I'll see what I can do to reproduce it
in the morning!

**Comment by stacey-gammon** [comment]
Trying to build docs for the first time in awhile and hitting this too.

```
staceys-mbp:docs gammon$ git pull origin master
From github.com:elastic/docs
 * branch            master     -> FETCH_HEAD
Already up to date.
staceys-mbp:docs gammon$ ./build_docs --doc README.asciidoc --open
Traceback (most recent call last):
  File "./build_docs", line 638, in <module>
    build_docker_image("build")
  File "./build_docs", line 85, in build_docker_image
    build = common_popen(cmd)
  File "./build_docs", line 517, in common_popen
    stderr=subprocess.STDOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
staceys-mbp:docs gammon$ 
```

Any ideas?

**Comment by bmorelli25** [comment]
I'm not able to reproduce this, sorry. Everything works as expected on my end.

@gtback may have some ideas.

**Comment by stacey-gammon** [comment]
Do I really need docker installed to build docs?

```
staceys-mbp:docs gammon$ docker --version
-bash: docker: command not found
```

**Comment by stacey-gammon** [comment]
Looks like that was it.

**Comment by gtback** [comment]
Glad you figured it out, @stacey-gammon. I realized the error message you're seeing isn't very intuitive at all (especially on Python 2), so I made #1856 to hopefully keep others from running into the same problem.
